import NavBar from "@/components/features/main-nav/main-nav";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex items-center bg-slate-50 md:h-[100dvh] lg:p-4 smd:overflow-y-auto">
        <main className="flex h-full w-full flex-col items-start bg-white shadow-md lg:flex-row lg:justify-between lg:rounded-lg">
          <NavBar />
          <div className="smd:w-full">{children}</div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
